# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class DhtListRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDhtListRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DhtListRequest()
        x.Init(buf, n + offset)
        return x

    # DhtListRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def DhtListRequestStart(builder): builder.StartObject(0)
def DhtListRequestEnd(builder): return builder.EndObject()
