# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class DhtShowResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDhtShowResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DhtShowResponse()
        x.Init(buf, n + offset)
        return x

    # DhtShowResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DhtShowResponse
    def Node(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .Node import Node
            obj = Node()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def DhtShowResponseStart(builder): builder.StartObject(1)
def DhtShowResponseAddNode(builder, node): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(node), 0)
def DhtShowResponseEnd(builder): return builder.EndObject()
