# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class Failure(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFailure(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Failure()
        x.Init(buf, n + offset)
        return x

    # Failure
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Failure
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

def FailureStart(builder): builder.StartObject(1)
def FailureAddMessage(builder, message): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)
def FailureEnd(builder): return builder.EndObject()
