# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class FeatureAddRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFeatureAddRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FeatureAddRequest()
        x.Init(buf, n + offset)
        return x

    # FeatureAddRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FeatureAddRequest
    def SketchId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # FeatureAddRequest
    def Feature(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .Feature import Feature
            obj = Feature()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def FeatureAddRequestStart(builder): builder.StartObject(2)
def FeatureAddRequestAddSketchId(builder, sketchId): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sketchId), 0)
def FeatureAddRequestAddFeature(builder, feature): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(feature), 0)
def FeatureAddRequestEnd(builder): return builder.EndObject()
