# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class FeatureAddResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFeatureAddResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FeatureAddResponse()
        x.Init(buf, n + offset)
        return x

    # FeatureAddResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def FeatureAddResponseStart(builder): builder.StartObject(0)
def FeatureAddResponseEnd(builder): return builder.EndObject()
