# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class FeatureRemoveResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFeatureRemoveResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FeatureRemoveResponse()
        x.Init(buf, n + offset)
        return x

    # FeatureRemoveResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def FeatureRemoveResponseStart(builder): builder.StartObject(0)
def FeatureRemoveResponseEnd(builder): return builder.EndObject()
