# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class GossipSketchResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGossipSketchResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GossipSketchResponse()
        x.Init(buf, n + offset)
        return x

    # GossipSketchResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def GossipSketchResponseStart(builder): builder.StartObject(0)
def GossipSketchResponseEnd(builder): return builder.EndObject()
