# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class GossipDhtResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGossipDhtResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GossipDhtResponse()
        x.Init(buf, n + offset)
        return x

    # GossipDhtResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def GossipDhtResponseStart(builder): builder.StartObject(0)
def GossipDhtResponseEnd(builder): return builder.EndObject()
