# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

class MessageType(object):
    DhtList = 0
    DhtShow = 1
    Failure = 2
    FeatureAdd = 3
    FeatureRemove = 4
    GossipDht = 5
    GossipSketch = 6
    PersistSketchSave = 7
    PersistSketchLoad = 8
    PipeCreate = 9
    PipeDelete = 10
    PipeWrite = 11
    Query = 12
    SketchCreate = 13
    SketchDelete = 14
    SketchList = 15
    SketchRemoveFeature = 16
    SketchShow = 17
    SketchWrite = 18

