# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class PersistSketchSaveResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPersistSketchSaveResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PersistSketchSaveResponse()
        x.Init(buf, n + offset)
        return x

    # PersistSketchSaveResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def PersistSketchSaveResponseStart(builder): builder.StartObject(0)
def PersistSketchSaveResponseEnd(builder): return builder.EndObject()
