# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class PersistSketchSaveRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPersistSketchSaveRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PersistSketchSaveRequest()
        x.Init(buf, n + offset)
        return x

    # PersistSketchSaveRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PersistSketchSaveRequest
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

def PersistSketchSaveRequestStart(builder): builder.StartObject(1)
def PersistSketchSaveRequestAddId(builder, id): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)
def PersistSketchSaveRequestEnd(builder): return builder.EndObject()
