# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class PersistSketchLoadResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPersistSketchLoadResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PersistSketchLoadResponse()
        x.Init(buf, n + offset)
        return x

    # PersistSketchLoadResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def PersistSketchLoadResponseStart(builder): builder.StartObject(0)
def PersistSketchLoadResponseEnd(builder): return builder.EndObject()
