# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class PipeWriteResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPipeWriteResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PipeWriteResponse()
        x.Init(buf, n + offset)
        return x

    # PipeWriteResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def PipeWriteResponseStart(builder): builder.StartObject(0)
def PipeWriteResponseEnd(builder): return builder.EndObject()
