# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class PipeDeleteResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPipeDeleteResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PipeDeleteResponse()
        x.Init(buf, n + offset)
        return x

    # PipeDeleteResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def PipeDeleteResponseStart(builder): builder.StartObject(0)
def PipeDeleteResponseEnd(builder): return builder.EndObject()
