# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class PipeDeleteRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPipeDeleteRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PipeDeleteRequest()
        x.Init(buf, n + offset)
        return x

    # PipeDeleteRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PipeDeleteRequest
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def PipeDeleteRequestStart(builder): builder.StartObject(1)
def PipeDeleteRequestAddId(builder, id): builder.PrependInt64Slot(0, id, 0)
def PipeDeleteRequestEnd(builder): return builder.EndObject()
