# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class PipeWriteRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPipeWriteRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PipeWriteRequest()
        x.Init(buf, n + offset)
        return x

    # PipeWriteRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PipeWriteRequest
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def PipeWriteRequestStart(builder): builder.StartObject(1)
def PipeWriteRequestAddId(builder, id): builder.PrependInt64Slot(0, id, 0)
def PipeWriteRequestEnd(builder): return builder.EndObject()
