# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class QueryResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsQueryResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QueryResponse()
        x.Init(buf, n + offset)
        return x

    # QueryResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # QueryResponse
    def BinEntries(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .BinEntry import BinEntry
            obj = BinEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # QueryResponse
    def BinEntriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def QueryResponseStart(builder): builder.StartObject(1)
def QueryResponseAddBinEntries(builder, binEntries): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(binEntries), 0)
def QueryResponseStartBinEntriesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def QueryResponseEnd(builder): return builder.EndObject()
