# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class SketchListResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSketchListResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SketchListResponse()
        x.Init(buf, n + offset)
        return x

    # SketchListResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SketchListResponse
    def Sketches(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Sketch import Sketch
            obj = Sketch()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SketchListResponse
    def SketchesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def SketchListResponseStart(builder): builder.StartObject(1)
def SketchListResponseAddSketches(builder, sketches): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sketches), 0)
def SketchListResponseStartSketchesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def SketchListResponseEnd(builder): return builder.EndObject()
