# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class SketchListRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSketchListRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SketchListRequest()
        x.Init(buf, n + offset)
        return x

    # SketchListRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def SketchListRequestStart(builder): builder.StartObject(0)
def SketchListRequestEnd(builder): return builder.EndObject()
