# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class SketchWriteResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSketchWriteResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SketchWriteResponse()
        x.Init(buf, n + offset)
        return x

    # SketchWriteResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def SketchWriteResponseStart(builder): builder.StartObject(0)
def SketchWriteResponseEnd(builder): return builder.EndObject()
