# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class SketchDeleteResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSketchDeleteResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SketchDeleteResponse()
        x.Init(buf, n + offset)
        return x

    # SketchDeleteResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def SketchDeleteResponseStart(builder): builder.StartObject(0)
def SketchDeleteResponseEnd(builder): return builder.EndObject()
