# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuffers

import flatbuffers

class SketchDeleteRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSketchDeleteRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SketchDeleteRequest()
        x.Init(buf, n + offset)
        return x

    # SketchDeleteRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SketchDeleteRequest
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

def SketchDeleteRequestStart(builder): builder.StartObject(1)
def SketchDeleteRequestAddId(builder, id): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)
def SketchDeleteRequestEnd(builder): return builder.EndObject()
